# Generated by Django 6.0.6 on 2026-06-13 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не может быть пустым', max_length=200, verbose_name='заголовок поста')),
                ('content', models.TextField(help_text='Не может быть пустым', verbose_name='содержание поста')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('vievs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.01, message='Цена должна быть больше 0')], verbose_name='количесиво просмотров')),
                ('is_published', models.BooleanField(default=False, help_text='Опубликован/черновик', verbose_name='Артикул')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
