# Generated by Django 6.0.6 on 2026-06-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Posts',
        ),
    ]
