# Generated by Django 6.0.6 on 2026-06-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_product_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Опубликован/черновик', verbose_name='Статус'),
        ),
    ]
