# Generated by Django 6.0.6 on 2026-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
