# Generated by Django 6.0.6 on 2026-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
