# Generated by Django 6.0.6 on 2026-06-12 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не может быть пустым', max_length=150, verbose_name='Название товара')),
                ('category', models.CharField(max_length=100, verbose_name='Категория товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Цена должна быть больше 0')], verbose_name='Цена')),
                ('sku', models.CharField(help_text='Уникальный артикул', max_length=50, unique=True, verbose_name='Артикул')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
